name: CI/CD Pipeline Spring App

on:
  push:
    branches: [ "main" ]

jobs:
  build-test-sonar-docker:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout
      - name: Checkout code
        uses: actions/checkout@v5

      # 2) Set JDK
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: "21"
          distribution: "temurin"

      # 3) Maven Build with aven
      - name: Build with Maven
        run: mvn clean package -DskipTests

      # 4) Run tests
      - name: Run Tests
        run: mvn test -Dspring.profiles.active=test

      # 5) SonarQube Scan
      - name: SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn sonar:sonar -Dsonar.projectKey=bonjour21 -Dsonar.host.url=http://3.85.173.70:9000 -Dsonar.login=$SONAR_TOKEN

      # 6) Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # 7) Login ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # 8) Build and push to ECR
      - name: Build, tag, and push image to ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: bonjour21
          IMAGE_TAG: latest
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

      # 9) Trivy Scan (from ECR)
      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "${{ steps.login-ecr.outputs.registry }}/bonjour21:latest"
      # 10) Configure kubectl with kubeconfig
      - name: Set up kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config

      # 11) Update image tag in manifest
      - name: Update deployment image
        run: |
          sed -i "s|image:.*|image: ${{ steps.login-ecr.outputs.registry }}/bonjour21:latest|" k8s/deployment.yaml
      - name: Copy k8s manifests to VM master
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "k8s/*"
          target: "/home/${{ secrets.SSH_USER }}/app/"

            # 10) Deploy on Kubernetes via SSH
      - name: Deploy to Kubernetes via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/bonjour/app  # dossier où tu veux mettre les manifests
            echo "Déploiement..."
            kubectl apply -f k8s/secret.yaml
            kubectl apply -f k8s/bonjours.yaml
            kubectl apply -f k8s/pv.yaml
            kubectl apply -f k8s/pvc.yaml
            kubectl apply -f k8s/deployment.yaml
            kubectl apply -f k8s/service.yaml
            kubectl rollout status deployment/spring-app
