name: CI/CD Pipeline Spring App

on:
  push:
    branches: [ "main" ]

jobs:
  build-test-sonar-docker:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout
      - name: Checkout code
        uses: actions/checkout@v5

      # 2) Set JDK
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: "21"
          distribution: "temurin"

      # 3) Maven Build with aven
      - name: Build with Maven
        run: mvn clean package -DskipTests

      # 4) Run tests
      - name: Run Tests
        run: mvn test

      # 5) SonarQube Scan
      - name: SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn sonar:sonar -Dsonar.projectKey=bonjour21 -Dsonar.host.url=http://54.196.134.174:9000 -Dsonar.login=$SONAR_TOKEN

      # 6) Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # 7) Login ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # 8) Build and push to ECR
      - name: Build, tag, and push image to ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: bonjour21
          IMAGE_TAG: latest
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

      # 9) Trivy Scan (from ECR)
      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "${{ steps.login-ecr.outputs.registry }}/bonjour21:latest"
