name: CI/CD Pipeline Spring App

on:
  push:
    branches: [ "main" ]

jobs:
  build-test-sonar-docker:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout
      - name: Checkout code
        uses: actions/checkout@v5

      # 2) Set JDK
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: "21"
          distribution: "temurin"

      # 3) Maven Build
      - name: Build with Maven
        run: mvn clean package -DskipTests

      # 4) SonarQube Scan
      - name: SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn sonar:sonar -Dsonar.projectKey=bonjour21 -Dsonar.host.url=http://3.85.173.70:9000 -Dsonar.login=$SONAR_TOKEN

      # 5) Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # 6) Login ECR Public
      - name: Login to Amazon ECR Public
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public

      # 7) Build & Push Docker Image (ECR Public)
      - name: Build, tag, and push image to ECR Public
        env:
          IMAGE: public.ecr.aws/p7m4r1k4/bonjour20:latest
        run: |
          docker build -t $IMAGE .
          docker push $IMAGE

      # 8) Trivy Scan
      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: public.ecr.aws/p7m4r1k4/bonjour20:latest

      # 9) Configure kubectl
      - name: Set up kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config

      # 10) Update image in Kubernetes manifest
      - name: Update deployment image
        run: |
          sed -i "s|image:.*|image: public.ecr.aws/p7m4r1k4/bonjour20:latest|" k8s/deployment.yaml

      # 11) Copy k8s manifests to master node
      - name: Copy k8s manifests to VM master
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "k8s/*"
          target: "/home/${{ secrets.SSH_USER }}/app/"

      # 12) Deploy on Kubernetes via SSH
      - name: Deploy to Kubernetes via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/${{ secrets.SSH_USER }}/app
            echo "DÃ©ploiement..."
            kubectl apply -f k8s/secret.yaml
            
            kubectl apply -f k8s/pv.yaml
            kubectl apply -f k8s/pvc.yaml
            kubectl apply -f k8s/bonjours.yaml
            kubectl apply -f k8s/deployment.yaml
            kubectl apply -f k8s/servicem.yaml
            kubectl apply -f k8s/services.yaml
